# fly.toml file generated for snowy-sky-7900 on 2023-01-28T21:48:50-05:00

app = "snowy-sky-7900"
procfile = "Procfile"
start = "cd client && npm start & cd ../server && nodemon server.js"

[env]
  PORT = "3333"
